allow-lan: true
dns:
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  enable: true
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - https://doh.pub/dns-query
  - https://223.6.6.6/dns-query
  use-hosts: true
log-level: warning
mixed-port: 9981
mode: rule
proxies:
- name: ç¾å›½è¥¿é›…å›¾
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: 21e62e0e-t7ksg0-tsluu1-1k2l4.se.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ç¾å›½è¥¿é›…å›¾2
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: aadfb5b6-t7ksg0-tsluu1-1k2l4.sv.plebai.net
  tls: true
  type: socks5
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ç¾å›½æ´›æ‰çŸ¶[CU]
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 15229
  server: f3b3e165-t7ksg0-tsluu1-1k2l4.cu.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ç¾å›½æ´›æ‰ç£¯HY
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  ports: 30000-60000
  server: 7def9d2c-t7ksg0-tsluu1-1k2l4.us.hyhuawei.com
  type: hysteria2
- name: ç¾å›½ç¡…è°·
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: 3d2c5fe3-t7ksg0-tsluu1-1k2l4.sj.gotochinatown.net
  tls: true
  type: socks5
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ç¾å›½ç¡…è°·2
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: be77be56-t7ksg0-tsluu1-1k2l4.sj.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ç¾å›½åœ£ä½•å¡
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: ebb0708d-t7ksg0-tsluu1-1k2l4.sjc.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ç¾å›½æ´›æ‰çŸ¶
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: 88c0a865-t7ksg0-tsluu1-1k2l4.los.gotochinatown.net
  tls: true
  type: socks5
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ç¾å›½æ´›æ‰çŸ¶2
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: 88c0a865-t7ksg0-tsluu1-1k2l4.los.gotochinatown.net
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡­ğŸ‡°é¦™æ¸¯ä¸­è½¬[CM]
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 5228
  server: bce9aa6f-t7ksg0-tsluu1-1k2l4.cm4.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“4
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: eeca5703-t7ksg0-tsluu1-1k2l4.hkt2.cdnhuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“3
  password: <password>
  port: 8443
  server: 589ebc3a-t7ksg0-tsluu1-1k2l4.hkt.cdnhuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- alterId: 2
  cipher: auto
  name: ğŸ‡­ğŸ‡° é¦™æ¸¯ç²¾å“
  network: ws
  port: 80
  server: 547d51ad-t7ksg0-tsluu1-1k2l4.hkt.gotochinatown.net
  tls: false
  type: vmess
  uuid: 479decec-0c49-11ef-85ee-f23c913c8d2b
  ws-headers:
    Host: broadcastlv.chat.bilibili.com
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
      (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
  ws-path: /
- name: ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“2
  password: <password>
  port: 443
  server: eeca5703-t7ksg0-tsluu1-1k2l4.hkt2.cdnhuawei.com
  tls: true
  type: socks5
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯HY02
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  ports: 30000-60000
  server: c11cdc32-t7ksg0-tsluu1-1k2l4.hk2.hyhuawei.com
  type: hysteria2
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯HY01
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  ports: 30000-60000
  server: 30f27b6c-t7ksg0-tsluu1-1k2l4.hk1.hyhuawei.com
  type: hysteria2
- name: ğŸ‡¬ğŸ‡§ è‹±å›½
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: 5cb6dbda-t7ksg0-tsluu1-1k2l4.uk.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡«ğŸ‡· æ³•å›½
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: 1d0c625d-t7ksg0-tsluu1-1k2l4.fr.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡©ğŸ‡ª å¾·å›½
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: cf1815ce-t7ksg0-tsluu1-1k2l4.de.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºš[CM]
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 31233
  server: ad6b76fc-t7ksg0-tsluu1-1k2l4.my.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡¹ğŸ‡­ æ³°å›½[CM]
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 32232
  server: 821a6957-t7ksg0-tsluu1-1k2l4.id.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡°ğŸ‡·éŸ©åœ‹[CT]
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 31433
  server: 2531d99a-t7ksg0-tsluu1-1k2l4.kr.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡¨ğŸ‡³ å°æ¹¾
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: 16327c68-t7ksg0-tsluu1-1k2l4.tw3.p5pv.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: 4e934687-t7ksg0-tsluu1-1k2l4.jp.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡®ğŸ‡© å°å°¼[CM]
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 32233
  server: 821a6957-t7ksg0-tsluu1-1k2l4.id.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬[CM]
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 27233
  server: bce9aa6f-t7ksg0-tsluu1-1k2l4.cm4.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: d049218a-t7ksg0-tsluu1-1k2l4.jp4.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡[CM]
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 17235
  server: bce9aa6f-t7ksg0-tsluu1-1k2l4.cm4.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: a70059a2-t7ksg0-tsluu1-1k2l4.sg.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡3
  password: 479decec-0c49-11ef-85ee-f23c913c8d2b
  port: 443
  server: b28be226-t7ksg0-tsluu1-1k2l4.sg3.oshuawei.com
  tls: true
  type: http
  username: 479decec-0c49-11ef-85ee-f23c913c8d2b
- alterId: 0
  cipher: auto
  name: çº¿è·¯å°‘è¯·æ›´æ¢è½¯ä»¶çœ‹å…¬å‘Š
  network: tcp
  port: 443
  server: hostloc.com
  tls: true
  type: vmess
  uuid: 479decec-0c49-11ef-85ee-f23c913c8d2b
proxy-groups:
- name: Ghelper
  proxies:
  - ğŸŒ å…¨çƒæ™ºèƒ½
  - ç¾å›½è¥¿é›…å›¾
  - ç¾å›½è¥¿é›…å›¾2
  - ç¾å›½æ´›æ‰çŸ¶[CU]
  - ç¾å›½æ´›æ‰ç£¯HY
  - ç¾å›½ç¡…è°·
  - ç¾å›½ç¡…è°·2
  - ç¾å›½åœ£ä½•å¡
  - ç¾å›½æ´›æ‰çŸ¶
  - ç¾å›½æ´›æ‰çŸ¶2
  - ğŸ‡­ğŸ‡° é¦™æ¸¯æ™ºèƒ½
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ä¸­è½¬[CM]
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“4
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“3
  - ğŸ‡­ğŸ‡° é¦™æ¸¯ç²¾å“
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“2
  - ğŸ‡­ğŸ‡° é¦™æ¸¯HY02
  - ğŸ‡­ğŸ‡° é¦™æ¸¯HY01
  - ğŸ‡¬ğŸ‡§ è‹±å›½
  - ğŸ‡«ğŸ‡· æ³•å›½
  - ğŸ‡©ğŸ‡ª å¾·å›½
  - ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºš[CM]
  - ğŸ‡¹ğŸ‡­ æ³°å›½[CM]
  - ğŸ‡°ğŸ‡·éŸ©åœ‹[CT]
  - ğŸ‡¨ğŸ‡³ å°æ¹¾
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
  - ğŸ‡®ğŸ‡© å°å°¼[CM]
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬[CM]
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡[CM]
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡3
  - AIä¸“ç”¨
  - çº¿è·¯å°‘è¯·æ›´æ¢è½¯ä»¶çœ‹å…¬å‘Š
  type: select
- interval: 7200
  name: ğŸŒ å…¨çƒæ™ºèƒ½
  proxies:
  - ç¾å›½è¥¿é›…å›¾
  - ç¾å›½è¥¿é›…å›¾2
  - ç¾å›½æ´›æ‰çŸ¶[CU]
  - ç¾å›½æ´›æ‰ç£¯HY
  - ç¾å›½ç¡…è°·
  - ç¾å›½ç¡…è°·2
  - ç¾å›½åœ£ä½•å¡
  - ç¾å›½æ´›æ‰çŸ¶
  - ç¾å›½æ´›æ‰çŸ¶2
  - ğŸ‡­ğŸ‡° é¦™æ¸¯æ™ºèƒ½
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ä¸­è½¬[CM]
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“4
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“3
  - ğŸ‡­ğŸ‡° é¦™æ¸¯ç²¾å“
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“2
  - ğŸ‡¬ğŸ‡§ è‹±å›½
  - ğŸ‡«ğŸ‡· æ³•å›½
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡3
  - çº¿è·¯å°‘è¯·æ›´æ¢è½¯ä»¶çœ‹å…¬å‘Š
  type: url-test
  url: http://www.gstatic.com/generate_204
- interval: 7200
  name: ğŸ‡­ğŸ‡° é¦™æ¸¯æ™ºèƒ½
  proxies:
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ä¸­è½¬[CM]
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“4
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“3
  - ğŸ‡­ğŸ‡° é¦™æ¸¯ç²¾å“
  - ğŸ‡­ğŸ‡°é¦™æ¸¯ç²¾å“2
  type: url-test
  url: http://www.gstatic.com/generate_204
- interval: 7200
  name: AIä¸“ç”¨
  proxies:
  - ç¾å›½è¥¿é›…å›¾
  - ç¾å›½è¥¿é›…å›¾2
  - ç¾å›½æ´›æ‰çŸ¶[CU]
  - ç¾å›½ç¡…è°·
  - ç¾å›½ç¡…è°·2
  - ç¾å›½åœ£ä½•å¡
  - ç¾å›½æ´›æ‰çŸ¶
  - ç¾å›½æ´›æ‰çŸ¶2
  - ğŸ‡¬ğŸ‡§ è‹±å›½
  - ğŸ‡«ğŸ‡· æ³•å›½
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬[CM]
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡[CM]
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡3
  type: url-test
  url: http://www.gstatic.com/generate_204
rules:
- DOMAIN-SUFFIX,ip-api.com,DIRECT
- DOMAIN-SUFFIX,ipip.net,DIRECT
- DOMAIN-SUFFIX,ip138.com,DIRECT
- DOMAIN-SUFFIX,skype.com,DIRECT
- DOMAIN-SUFFIX,skype.comedge.skype.net,DIRECT
- DOMAIN-SUFFIX,skypeassets.com,DIRECT
- DOMAIN-SUFFIX,skypeforbusiness.com,DIRECT
- DOMAIN-SUFFIX,cdnkuaisou.com,DIRECT
- DOMAIN-SUFFIX,cnkuaishou.com,DIRECT
- DOMAIN-SUFFIX,cmhuawei.com,DIRECT
- DOMAIN-SUFFIX,cmhuawei.com,DIRECT
- DOMAIN-SUFFIX,cdnhuawei.com,DIRECT
- DOMAIN-SUFFIX,viphuawei.com,DIRECT
- DOMAIN-SUFFIX,chromeapi.com,DIRECT
- DOMAIN-SUFFIX,paypal.com,DIRECT
- DOMAIN-SUFFIX,alipay.com,DIRECT
- DOMAIN-SUFFIX,airwallex.com,DIRECT
- DOMAIN-SUFFIX,stripe.com,DIRECT
- DOMAIN-SUFFIX,wooshpay.com,DIRECT
- DOMAIN-SUFFIX,payssion.com,DIRECT
- DOMAIN-SUFFIX,chrapi.com,DIRECT
- DOMAIN-SUFFIX,firapi.com,DIRECT
- DOMAIN-SUFFIX,gheapi.com,DIRECT
- DOMAIN-SUFFIX,broapi.com,DIRECT
- DOMAIN-SUFFIX,edgapi.com,DIRECT
- DOMAIN-SUFFIX,browserapi.net,DIRECT
- DOMAIN-SUFFIX,cnsync.com,DIRECT
- DOMAIN-SUFFIX,on1t.com,DIRECT
- DOMAIN-SUFFIX,chromeapi.net,DIRECT
- DOMAIN-SUFFIX,copydesign.net,DIRECT
- DOMAIN-SUFFIX,jy3p.com,DIRECT
- DOMAIN-SUFFIX,p5pv.com,DIRECT
- DOMAIN-SUFFIX,z7zi.com,DIRECT
- DOMAIN-SUFFIX,j2ai.com,DIRECT
- DOMAIN-SUFFIX,alrihla.net,DIRECT
- DOMAIN-SUFFIX,sphinxsearch.net,DIRECT
- DOMAIN-SUFFIX,skype.com,DIRECT
- DOMAIN-SUFFIX,cdnhuawei.com,DIRECT
- DOMAIN-SUFFIX,cdnkuaishou.com,DIRECT
- DOMAIN-SUFFIX,chromeapi.net,DIRECT
- DOMAIN-KEYWORD,google,Ghelper
- DOMAIN-SUFFIX,ggpht.com,Ghelper
- DOMAIN-SUFFIX,gmail.com,Ghelper
- DOMAIN-SUFFIX,gvt2.com,Ghelper
- DOMAIN-SUFFIX,gvt3.com,Ghelper
- DOMAIN-SUFFIX,chrome.com,Ghelper
- DOMAIN-SUFFIX,wikipedia.org,Ghelper
- DOMAIN-SUFFIX,wikimedia.org,Ghelper
- DOMAIN-SUFFIX,appspot.com,Ghelper
- DOMAIN-SUFFIX,android.com,Ghelper
- DOMAIN-SUFFIX,github.com,Ghelper
- DOMAIN-SUFFIX,gitbook.com,Ghelper
- DOMAIN-SUFFIX,kaggle.com,Ghelper
- DOMAIN-SUFFIX,arxiv.org,Ghelper
- DOMAIN-SUFFIX,wiktionary.org,Ghelper
- DOMAIN-SUFFIX,blogger.com,Ghelper
- DOMAIN-KEYWORD,google,Ghelper
- DOMAIN-KEYWORD,youtube,Ghelper
- DOMAIN-SUFFIX,ggpht.com,Ghelper
- DOMAIN-SUFFIX,gmail.com,Ghelper
- DOMAIN-SUFFIX,gvt2.com,Ghelper
- DOMAIN-SUFFIX,gvt3.com,Ghelper
- DOMAIN-SUFFIX,chrome.com,Ghelper
- DOMAIN-SUFFIX,wikipedia.org,Ghelper
- DOMAIN-SUFFIX,wikimedia.org,Ghelper
- DOMAIN-SUFFIX,appspot.com,Ghelper
- DOMAIN-SUFFIX,android.com,Ghelper
- DOMAIN-SUFFIX,github.com,Ghelper
- DOMAIN-SUFFIX,gitbook.com,Ghelper
- DOMAIN-SUFFIX,kaggle.com,Ghelper
- DOMAIN-SUFFIX,arxiv.org,Ghelper
- DOMAIN-SUFFIX,wiktionary.org,Ghelper
- DOMAIN-SUFFIX,blogger.com,Ghelper
- DOMAIN-SUFFIX,youtu.be,Ghelper
- DOMAIN-SUFFIX,ytimg.com,Ghelper
- DOMAIN-SUFFIX,youtube.com,Ghelper
- DOMAIN-SUFFIX,instagram.com,Ghelper
- DOMAIN-SUFFIX,twitter.com,Ghelper
- DOMAIN-SUFFIX,t.co,Ghelper
- DOMAIN-SUFFIX,facebook.com,Ghelper
- DOMAIN-SUFFIX,telegram.org,Ghelper
- DOMAIN-SUFFIX,whatsapp.com,Ghelper
- DOMAIN-SUFFIX,whatsapp.net,Ghelper
- DOMAIN-SUFFIX,linkedin.com,Ghelper
- DOMAIN-SUFFIX,licdn.com,Ghelper
- DOMAIN-SUFFIX,trkn.us,Ghelper
- DOMAIN-SUFFIX,cedexis.com,Ghelper
- DOMAIN-SUFFIX,ip.sb,Ghelper
- DOMAIN-SUFFIX,ip.net,Ghelper
- DOMAIN-SUFFIX,openai.com,Ghelper
- DOMAIN-SUFFIX,auth0.com,Ghelper
- DOMAIN-SUFFIX,featuregates.org,Ghelper
- DOMAIN-SUFFIX,statsigapi.net,Ghelper
- DOMAIN-SUFFIX,intercom.io,Ghelper
- DOMAIN-SUFFIX,intercomcdn.com,Ghelper
- DOMAIN-SUFFIX,sentry.io,Ghelper
- DOMAIN-SUFFIX,sentry.dev,Ghelper
- DOMAIN-SUFFIX,oaistatic.com,Ghelper
- DOMAIN-SUFFIX,oaiusercontent.com,Ghelper
- DOMAIN-SUFFIX,chatgpt.com,Ghelper
- DOMAIN-SUFFIX,chatgpt-async-webps-prod-southcentralus-6.webpubsub.azure.com,Ghelper
- DOMAIN-SUFFIX,claude.ai,Ghelper
- DOMAIN-SUFFIX,anthropic.com,Ghelper
- DOMAIN-SUFFIX,intercomcdn.com,Ghelper
- DOMAIN-SUFFIX,intercom.io,Ghelper
- DOMAIN-SUFFIX,bing.com,Ghelper
- DOMAIN-SUFFIX,microsoftonline.com,Ghelper
- DOMAIN-SUFFIX,live.com,Ghelper
- DOMAIN-SUFFIX,msecnd.net,Ghelper
- DOMAIN-SUFFIX,msn.com,Ghelper
- DOMAIN-SUFFIX,bingapis.com,Ghelper
- DOMAIN-SUFFIX,bing.net,Ghelper
- DOMAIN-SUFFIX,windows.com,Ghelper
- DOMAIN-SUFFIX,microsoft.com,Ghelper
- DOMAIN-SUFFIX,linkedin.com,Ghelper
- DOMAIN-SUFFIX,licdn.com,Ghelper
- DOMAIN-SUFFIX,trkn.us,Ghelper
- DOMAIN-SUFFIX,cedexis.com,Ghelper
- GEOIP,CN,DIRECT
- MATCH, Ghelper
